# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 01:03
from __future__ import unicode_literals

import brazil_fields.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('cnpj', brazil_fields.fields.CNPJField(max_length=14)),
                ('razao_social', models.CharField(max_length=200, verbose_name='razão social')),
                ('nome_fantasia', models.CharField(max_length=100, verbose_name='nome fantasia')),
            ],
            options={
                'verbose_name_plural': 'empresas',
                'verbose_name': 'empresa',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='empresa',
            field=models.ManyToManyField(to='geral.Empresa'),
        ),
    ]
